spring.application.name=email-signature
google.sheets.application-name=Wedo Email Signature
google.sheets.spreadsheet-id=1gLNRFchOwv5HLOCV50octxC05gJ4yBXq61Pmn7UTL54
google.sheets.range=Colaboradores!A:E
google.sheets.credentials-path=${GOOGLE_SHEETS_CREDENTIALS_PATH}